### ISSUE TITLE
Missing -W value type

### ISSUE THREAD

**Issue by avezinaATastus** [the-tcpdump-group/tcpdump-htdocs#15]
https://github.com/the-tcpdump-group/tcpdump-htdocs/blob/12d33656d0f3a84a13dcb3d64641d911e4736880/manpages/tcpdump.1.txt#L504

I was reading the man and was wondering why I had an error at execution : 
`tcpdump: invalid number of output files -z `

There's a 'count' missing from the manpage at the -w parameter.

I'm expecting to read : 

> -W _count_
>     Used in conjunction with the -C option, this will limit the number of files created to the specified number, and begin overwriting ...

But we read : 
> -W
>     Used in conjunction with the -C option, this will limit the number of files created to the specified number, and begin overwriting ...

**Comment by infrastation** [comment]
Commit the-tcpdump-group/tcpdump@12cf799 fixes this, thank you. The correction is already on the web-site.
