### ISSUE TITLE
add /manpages/index.html

### ISSUE THREAD

**Issue by mcr** [the-tcpdump-group/tcpdump-htdocs#22]
Add an index.html to the /manpages directory.
Some servers have directory indexing on, but we shouldn't depend upon that.

**Comment by infrastation** [comment]
Michael, let me mention that this is not the first attempt to discuss this idea. Last time was in 2020 between yourself, myself, Guy and Francois-Xavier. On 16 Aug 2020 I asked you by e-mail to clarify a few particular aspects. You acknowledged the receipt, but did not clarify, as far as I understand. If you wish to discuss the same idea again, my obvious response is to ask the same questions again and to expect answers. I hope this does not look unreasonable.

If you wish to raise this idea again, please study that e-mail with attention. The points I made at the time still apply. If you find it more convenient to follow-up by e-mail on the old e-mail thread, that would be fine with me (in which case this issue would have no purpose). If you prefer to continue the discussion in this issue on github.com, let me suggest (and you have my permission) to post a full copy of my message here. If you choose not to follow up, I will close this request before long.

**Comment by mcr** [comment]
Using an issue to keep track of an open discussion seems like a good idea.
This is the only message I have from 16-Aug-2020 in my outbox.
Perhaps this is not the right message.

<pre>
Subject: Re: [www.tcpdump.org] About third party embeds sites
Date: Sun, 16 Aug 2020 15:36:55 -0400


[[PGP Signed Part:Undecided]]

Denis Ovsienko <denis@ovsienko.info> wrote:
    > [...]
    >> Well, I really like static flat web sites that can be hosted anywhere
    >> at any time without any kind of fancy configuration.

    > Regarding server-agnostic hosting, your personal preference is
    > perfectly appropriate for your personal web-site (which actually runs
    > on Apache httpd 2.4, BTW). My preference is not quite the same, but it
    > is perfectly appropriate for my personal web-site.

Not really my personal preference, but I can see how it sounds like that.
If we need to make local server tweaks, or run local software (CGIs), then
the ability to just move the site to any place quickly and easily is gone.
Even github recognizes this is important for projects:  that's why jekyll.

Is it apache 2.4 that bothers you?  We can run whatever.

    >> I don't remember what other challenges it has caused.

    > You do not remember this pain because you have not experienced it, not
    > recently at least. Please mind that in recent years I have been doing
    > most of the generic maintenance work to keep the contents of
    > www.tcpdump.org in acceptable shape. Since you hear time after time that
    > nginx in this setup causes regular unnecessary pain when I have to use
    > year 1990 solution space (static files) for year 1995 problem space
    > (access control, indices, redirects), please either:

    > * trust me and remove nginx from the solution space (only you control
    > the DNS zone), or

    > * take care to explain in proper detail why in your opinion keeping the
    > part-functional nginx server is such a high priority for the project
    > that it is worth the inconvenience.

I'm still a bit lost.
What problems is the copy at www.us.tcpdump.org (hosted by the Gerald and the
wireshark crew) causing?   You don't get to tweak the nginx configuration.
We used to have 15 mirrors, back when bandwidth was expensive.

Is this about .htaccess files being visible?
Probably we shouldn't depend upon any Option foobar, particularly Indexes if we can avoid it.

    > As explained several times before, I would strongly prefer just to move
    > into Apache-only solution space, even if that costs me $5 per month. My
    > time is worth much more than that, and it is August 2020 now.

yes, you've offered this before, and I recall the conversation, but not the details as to why?

I'll happily pay four times that directly, but it doesn't even begin to pay for your time to maintain such a thing.  You'd be the only one doing that.

    > And, because it is important to keep the street two-way, if a technical
    > choice of mine makes you unhappy and has no apparent benefits to the
    > project, please say it.

    >> So, your plan would be just fine, but pull the status files from some
    >> new status.tcpdump.org, which is also on bpf.tcpdump.org, but isn't
    >> mirrored.
    >>
    >> Or, my plan that I suggested on the list.

    > Regarding the specific way to arrange the status badges, I would be fine
    > with anybody implementing it their preferred way, so long as:

    > * the web-site continues to have all up-to-date badges
    > * the new solution does not introduce major housekeeping complications
    > * when it breaks, the author comes and fixes it promptly

    > I would also be fine to leave the badges as they are for now, or, as
    > the last resort, to remove them if that's the only way to avoid
    > unnecessary tensions.

I'm with you.  I want the status badges there.
I am not particularly concerned with IP address leakage, but I respect that Francis is.  I'm not interested in a more complex scheme.

</pre>

**Comment by mcr** [comment]
Also, according to: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

github can now do IPv6 for their hosting service.    
Reworking everything to markdown and jekyll would probably lower the barrier to contribution.
It's another option which I would not have previously considered, because of lack of IPv6.
