### ISSUE TITLE
HTTPS version of www.tcpdump.org unavailable

### ISSUE THREAD

**Issue by mcginty** [the-tcpdump-group/tcpdump-htdocs#6]
In a bout of funny-to-me irony, it looks like one cannot safely download the TCPdump distribution (there's no HTTPS site). At the moment, https://www.tcpdump.org just goes to wireshark's distribution page.

Seems like right now the only way to securely get the source is via github at the moment.

Thanks so much for your work.

**Comment by guyharris** [comment]
Currently, it fails with Safari and Chrome on my Mac.  Michael?

**Comment by infrastation** [comment]
Michael has sorted this, closing.
