### ISSUE TITLE
no libpcap 1.7.4 changelog

### ISSUE THREAD

**Issue by mischief** [the-tcpdump-group/tcpdump-htdocs#7]
the changelog url provided on tcpdump.org for the libpcap 1.7.4 release contains no changelog for 1.7.4 or any instance of the string '1.7.4'. am i confused or is this an error?

http://www.tcpdump.org/libpcap-changes.txt

**Comment by mcr** [comment]
Nick Owens <notifications@github.com> wrote:
    > the changelog url provided on tcpdump.org for the libpcap 1.7.4 release
    > contains no changelog for 1.7.4 or any instance of the string '1.7.4'. am i
    > confused or is this an error?

    > http://www.tcpdump.org/libpcap-changes.txt

Hi, looks like the tcpdump-htdocs repo on my desktop where I would have
pushed that change out was in a state of conflict, which I didn't resolve.
Please see http://www.ca.tcpdump.org/libpcap-changes.txt
The mirrors will catch up overnight.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by mischief** [comment]
looks fixed, thanks
